### ISSUE TITLE
Code Refactoring

### ISSUE THREAD

**Issue by SharathRaparthy** [IvLabs/stagewise-knowledge-distillation#2]
If possible, can you refactor your code? It's difficult for me to follow the code sometimes.

**Comment by navidpanchi** [comment]
Yep will start going through it tomorrow.

**Comment by akshaykvnit** [comment]
@navidpanchi will you open a PR?

**Comment by navidpanchi** [comment]
Yes

**Comment by SharathRaparthy** [comment]
Please do the image classification refactoring as well.
