### ISSUE TITLE
Large size of repository

### ISSUE THREAD

**Issue by akshaykvnit** [IvLabs/stagewise-knowledge-distillation#7]
The repository is very large to download (around 150 MB). Most of this is in the `.git` file because of the large number of commits and multiple branches. Is there a way to reduce the size? because cloning the repo will take up a lot more space (the actual code is barely 2 or 3 MB). 
@SharathRaparthy @navidpanchi

**Comment by navidpanchi** [comment]
Okay so maybe we can create a back up repo and delete the old commits from here once we are done refactoring and testing.

**Comment by SharathRaparthy** [comment]
Yes: check [this](https://link.medium.com/DgKNuUz2x5)

**Comment by akshaykvnit** [comment]
There is another thing. There is a 'squash and merge' option in PRs. That combines the entire branch commits into a single commit. So, that will reduce the number of commits (for further PRs).
